### ISSUE TITLE
Use proxy to get access token

### ISSUE THREAD

**Issue by rexave** [spring-projects/spring-security-oauth2-boot#81]
Bug report/Enhancement

Version used : 2.1.2.RELEASE
While using the sample provided by @spencergibb at https://github.com/spring-cloud-samples/sample-gateway-oauth2login , i couldn't configure the gateway to use http proxy.

The webclient used for that isn't configurable. 
`org.springframework.security.oauth2.client.endpoint.WebClientReactiveAuthorizationCodeTokenResponseClient#webClient`
The webclient used isn't the one configured by the gateway with : 
```
spring: 
  cloud:
    gateway:
      httpclient:
        proxy:
          host: myProxy.com
          port: 1234
      enabled: true
```

Can you make this configurable or inject a webclient bean to let use configure it ?
